# Generated by Django 5.0.3 on 2024-04-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_question_answers_test_creator_test_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='TestsToQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.questionshort')),
                ('testID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.testshort')),
            ],
        ),
    ]
