# Generated by Django 5.0.3 on 2024-04-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_questionshort_testshort_teststoquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testshort',
            name='questions',
            field=models.ManyToManyField(to='tests.questionshort'),
        ),
        migrations.DeleteModel(
            name='TestsToQuestions',
        ),
    ]
