# Generated by Django 5.0.3 on 2024-05-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testshort_questions_delete_teststoquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testshort',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
